# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '05json 解析' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking'
  # Pods for 05json 解析

end
