# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '青云微博' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 青云微博
pod 'AFNetworking', '~> 3.0'
pod 'FMDB'
pod 'MBProgressHUD'
end
