source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SmartLC' do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.1'
pod 'SDCycleScrollView','~> 1.64'
end
